### PR TITLE
Feature/fuzzy stacked win detection

### PR DESCRIPTION
**Pull request by AdamWagner**
Support iTerm (and other apps that constrict window dimensions) by rounding window frames to (configurable) fuzzFactor before equality comparison.

Addresses need in https://github.com/AdamWagner/stackline/issues/32.

Built on top of https://github.com/AdamWagner/stackline/pull/36

### CODE REVIEW

**Comment by Coobaha** [comment]
hey @AdamWagner i tested this branch, here is my diff to make it work

fixes fuzz rounding and clicks were registered only on top of the icon, probably magic offset should be calculated from config variables.

```diff
Index: stackline/window.lua
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- stackline/window.lua	(revision 3876f8de906e089f74f9a968dcd5fefeb1020195)
+++ stackline/window.lua	(date 1600054643343)
@@ -361,11 +361,11 @@
 
     local fuzzFactor = stackline.config:get('frameFuzz')
     local roundToFuzzFactor = u.partial(u.roundToNearest, fuzzFactor)
+	print(hsWin:title())
 
     local f = hsWin:frame():floor():gettable()
     local ff = u.map(f, roundToFuzzFactor)
 
-    print(hsWin:title(), 'round to neartest 5:', u.roundToNearest(5, 33))
     u.p(f)
     u.p(ff)
 
Index: lib/utils.lua
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/utils.lua	(revision 3876f8de906e089f74f9a968dcd5fefeb1020195)
+++ lib/utils.lua	(date 1600055571234)
@@ -366,7 +366,10 @@
     end
 end -- }}}
 
-function utils.roundToNearest(roundNum, num) -- {{{
+function utils.roundToNearest(num, roundNum) -- {{{
+    if num < roundNum then
+        return 0
+    end
     if num % roundNum >= roundNum / 2 then
         return num - num % roundNum + roundNum
     else
Index: stackline/stackline.lua
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- stackline/stackline.lua	(revision 3876f8de906e089f74f9a968dcd5fefeb1020195)
+++ stackline/stackline.lua	(date 1600055571237)
@@ -42,7 +42,7 @@
         showIcons = true,
         enableTmpFixForHsBug = true,
 
-        -- Window frames are rounded to fuzzFactor before equality comparison. 
+        -- Window frames are rounded to fuzzFactor before equality comparison.
         -- ~30 is needed to support stacks w/ iTerm
         frameFuzz = 30,
     }
@@ -106,12 +106,4 @@
     stackline.refreshClickTracker()
 end):start() -- }}}
 
--- Delayed start (stackline module needs to be loaded globally before it can reference its own methods)
--- TODO: Add instructions to README.md to call stackline:start(userPrefs) from init.lua, and remove this.
-hs.timer.doUntil(function() -- {{{
-    return stackline.manager
-end, function()
-    stackline.start()
-end, 0.1) -- }}}
-
 return stackline
Index: stackline/stack.lua
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- stackline/stack.lua	(revision 3876f8de906e089f74f9a968dcd5fefeb1020195)
+++ stackline/stack.lua	(date 1600055571228)
@@ -20,7 +20,7 @@
     end, -- }}}
 
     frame = function(self) -- {{{
-        -- All stacked windows have the same dimensions, 
+        -- All stacked windows have the same dimensions,
         -- so the 1st Hs window's frame is ~= to the stack's frame
         -- TODO: Incorrect when the 1st window has min-size < stack width. See ./query.lua:104
         return self.windows[1]._win:frame()
@@ -69,10 +69,12 @@
     end, -- }}}
 
     getWindowByPoint = function(self, point) -- {{{
+		local p = hs.geometry.copy(point)
+		p.y = point.y - 22
         local foundWin = u.filter(self.windows, function(w)
             local indicatorEls = w.indicator:canvasElements()
             local wFrame = hs.geometry.rect(indicatorEls[1].frame)
-            return point:inside(wFrame)
+            return p:inside(wFrame)
         end)
 
         if #foundWin > 0 then
```

**Comment by Coobaha** [comment]
hey @AdamWagner my diff is very random, i was hacking around to make it work without really focusing on proper code :) Please pardon me if it confused you!

I will test first case and will tell exact reasons why it swapped it soon. 

Regarding second question: basically icons very capturing clicks only when top part of icon was clicked. But configurable and magic number I only meant my -22px offset to shift clickable area. I bet that it can be calculated from other variables and logic of placing click indicators.

**Comment by AdamWagner** [comment]
@Coobaha I totally get it. Sorry for the homework assignment ;-)

>Regarding second question: basically icons very capturing clicks only when top part of icon was clicked. But configurable and magic number I only meant my -22px offset to shift clickable area. I bet that it can be calculated from other variables and logic of placing click indicators.

Odd, I cannot reproduce this behavior. When I click the bottom 1 - 2 pixels of an icon, the expected window focuses. Maybe we can revisit this icon-clicking issue after this branch is merged into master just to be sure we're testing the same code? This PR is currently up-to-date with my local version, btw.

**Comment by Coobaha** [comment]
So issue with stack detection is happening when yabai space has padding

Output with padding

 ```
2020-09-19 07:16:53: Hammerspoon Console
2020-09-19 07:16:53: -- Loading extension: inspect
2020-09-19 07:16:53: {
  h = 1398,
  w = 2540,
  x = 10,
  y = 32
}
2020-09-19 07:16:53: {
  h = 1410,
  w = 2550,
  x = 0,
  y = 30
}
2020-09-19 07:16:53: EventViewer
2020-09-19 07:16:53: {
  h = 1398,
  w = 2540,
  x = 10,
  y = 32
}
2020-09-19 07:16:53: {
  h = 1410,
  w = 2550,
  x = 0,
  y = 30
}
2020-09-19 07:16:53: Default (bash)
2020-09-19 07:16:53: {
  h = 1392,
  w = 2538,
  x = 10,
  y = 32
}
2020-09-19 07:16:53: {
  h = 1380,
  w = 2550,
  x = 0,
  y = 30
}
```
Output without padding
```
2020-09-19 07:18:57: Hammerspoon Console
2020-09-19 07:18:57: -- Loading extension: inspect
2020-09-19 07:18:57: {
  h = 1417,
  w = 2560,
  x = 0,
  y = 23
}
2020-09-19 07:18:57: {
  h = 1410,
  w = 2550,
  x = 0,
  y = 30
}
2020-09-19 07:18:57: EventViewer
2020-09-19 07:18:57: {
  h = 1417,
  w = 2560,
  x = 0,
  y = 23
}
2020-09-19 07:18:57: {
  h = 1410,
  w = 2550,
  x = 0,
  y = 30
}
2020-09-19 07:18:57: Default (bash)
2020-09-19 07:18:57: {
  h = 1417,
  w = 2560,
  x = 0,
  y = 23
}
2020-09-19 07:18:57: {
  h = 1410,
  w = 2550,
  x = 0,
  y = 30
}
```

iTerm height is different in this case 😢 

This is how clicking behaves for me in your branch
screencast 2020-09-19 07-01-27

**Comment by Coobaha** [comment]
Maybe stackId should be `x|y` only? Not sure if colliding stacks (when xy is equal but heights or widths are different) is possible or needed to be treated uniquely in this case..

**Comment by AdamWagner** [comment]
Thanks for the update @Coobaha 

Using `x|y` would mostly work, but breaks when using `zoom-parent` on a window near a stack. (Zoom parent can make the top-left corner of a window coincident with a stack of which it is not a member). If you don't use zooming, this wouldn't be an issue. Maybe using just `x|y` could be a config option, then, but I don't want to make it the default.

So, I totally rewrote how windows are grouped into stacks today. 

And then scrapped it ;-)

The experimental change made everything _way_ more complicated and led to much worse results (and non-deterministic bugs). Somewhat frustrated, I took a long shot by increasing the `frameFuzz` value to 200 (from a mere 15) and making the rounding function more simple/predictable. Surprisingly, the results from this were _way_ better. It's pretty resilient to minor differences in window size (the "iTerm" issue), and doesn't seem to cause any negative side effects (that I've seen). 

The change is live here if you want to check it out. 

--

PS – thanks for sharing the screen recording of clicking. Am I interpreting it correctly that you're able to click anywhere on an icon to focus a window now?

**Comment by Coobaha** [comment]
with my changes (-22px) yea, click works just fine. Gif is without offset logic. I was clicking 2 and 4 icons top part, when 1 and 3 icon were clicked clicks were captured by 2 and 4 icons 

I will check the recent changes later, kudos for that 👍

**Comment by AdamWagner** [comment]
@Coobaha any feedback on the updated fuzzy frame matching? 
FYI, I submitted an FR for `yabai` to provide the ability to query stacks directly. If added, this would resolve this challenge once and for all ;-) 
https://github.com/koekeishiya/yabai/issues/672

**Comment by AdamWagner** [comment]
@Coobaha Just following up to  see if you've had a chance to test out the latest version. 

And no worries if you have other things going on … I'm just checking. I think the basic changes here will be merged as part of https://github.com/AdamWagner/stackline/pull/45 anyway.

**Comment by Coobaha** [comment]
Hey, I tested it around when you've made the changes but forgot to reply back 🙈  It was working fine, but I was not using stacks/stackline recently - so my testing was not that deep.

**Comment by AdamWagner** [comment]
Great to hear, thanks @Coobaha !

**Comment by Coobaha** [comment]
@AdamWagner sorry for pinging you back, but i found the root cause of wrong indicator positions/clicks - it depends on menubar. If it is hidden in settings - everything works as expected. If visible - extra offset is added. Please check attached video


https://user-images.githubusercontent.com/2446638/107145775-86818c00-694c-11eb-877a-92ed337c023f.mp4

**Comment by AdamWagner** [comment]
@Coobaha I'm bummed that I missed your original comment… but happy that the fix was less than a 1 line change!

See: https://github.com/AdamWagner/stackline/pull/80

This is merged to main now. Sorry for not fixing this sooner!

**Pull request merged**
